# Generated by Django 4.1.7 on 2023-03-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
