# Generated by Django 4.1.5 on 2023-03-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0012_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
