# Generated by Django 4.1.5 on 2023-03-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0019_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
