# Generated by Django 4.1.5 on 2023-03-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0020_delete_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('notice', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
